[package]
name = "celery-rs-core"
version = "0.1.0"
authors = ["Andrew Evans <asevans48@gmail.com>"]
edition = "2018"

[dependencies]
amiquip = "0.3.2"
amq-protocol = "3.0.0"
serde = "1.0.102"
serde_json = "1.0.40"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
hostname = "0.1.5"